config/routes.rb
Rails.application.routes.draw do
  resources :needs
  resources :institutions
  root to: 'pages#home'

  get "/search" => "pages#search"
  get "/criadores" => "pages#criadores"
  get "/contato" => "pages#contato"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
end

app/models/institution.rb
class Institution < ApplicationRecord
  has_and_belongs_to_many :needs
end

app/models/need.rb
class Need < ApplicationRecord
  has_and_belongs_to_many :institutions, dependent: :destroy
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :states
  has_many :cities, through: :states
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :region
  has_many :cities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: [:show, :edit, :update, :destroy]

  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.all
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
    @states = State.all
    @cities = City.all
  end

  # GET /institutions/1/edit
  def edit
    @states = State.all
    @cities = City.all
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(institution_params)

    respond_to do |format|
      if @institution.save
        format.html { redirect_to @institution, notice: 'Institution was successfully created.' }
        format.json { render :show, status: :created, location: @institution }
      else
        format.html { render :new }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutions/1
  # PATCH/PUT /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution.destroy
    respond_to do |format|
      format.html { redirect_to institutions_url, notice: 'Institution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institution_params
      params.require(:institution).permit(:name, :email, :phone, :address, :city, :state, :needs, :description, need_ids:[])
    end
end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController
  before_action :set_need, only: [:show, :edit, :update, :destroy]

  # GET /needs
  # GET /needs.json
  def index
    @needs = Need.all
  end

  # GET /needs/1
  # GET /needs/1.json
  def show
  end

  # GET /needs/new
  def new
    @need = Need.new
  end

  # GET /needs/1/edit
  def edit
  end

  # POST /needs
  # POST /needs.json
  def create
    @need = Need.new(need_params)

    respond_to do |format|
      if @need.save
        format.html { redirect_to @need, notice: 'Need was successfully created.' }
        format.json { render :show, status: :created, location: @need }
      else
        format.html { render :new }
        format.json { render json: @need.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /needs/1
  # PATCH/PUT /needs/1.json
  def update
    respond_to do |format|
      if @need.update(need_params)
        format.html { redirect_to @need, notice: 'Need was successfully updated.' }
        format.json { render :show, status: :ok, location: @need }
      else
        format.html { render :edit }
        format.json { render json: @need.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /needs/1
  # DELETE /needs/1.json
  def destroy
    @need.destroy
    respond_to do |format|
      format.html { redirect_to needs_url, notice: 'Need was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_need
      @need = Need.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def need_params
      params.require(:need).permit(:necessidade)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @states = State.all
    @cities = City.all
  end

  def search
    @institutions = Institution
      .where('state LIKE ? AND city LIKE ? AND necessidade LIKE ?', params[:state], params[:city][:city_id], params[:need])
      .joins(:needs)
  end

  def criadores
  end

  def contato
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/needs_helper.rb
module NeedsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/institutions/_form.html.erb
<%= form_with(model: institution, local: true) do |form| %>
  <% if institution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

      <ul>
      <% institution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <label for="name">Nome</label>
        <%= form.text_field :name, class: "form-control"%>
      </div>
      
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="email">E-mail</label>
          <%= form.text_field :email, class: "form-control" %>
        </div>
      
        <div class="form-group col-md-6">
          <label for="phone">Telefone</label>
          <%= form.text_field :phone, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <label for="address">Endereço</label>
        <%= form.text_field :address, class: "form-control" %>
      </div>
    </div>
  
    <div class="col-md-6">
      <div class="form-row">
        <div class="form-group col-md-4">
          <label for="state">Estado</label>
          <%= form.collection_select(:state, @states, :name, :acronym, {include_blank: false}, {:id => 'states_sected', :class => "form-control"}) %>
        </div>

        <div class="form-group col-md-8">
          <label for="city">Cidade</label>
          <%= form.grouped_collection_select :city, State.order(:name), :cities, :acronym, :name, :name, {include_blank: false}, class: "form-control" %>
        </div>      
      </div>

      <div class="form-group">
        <label for="description">Descrição</label>
        <%= form.text_area :description, size: '50x5', class: "form-control" %>
      </div>            
    </div>
    
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <div class="row">
          <div class="col-2">
            <label for="needs">Necessidades</label>
          </div>
          <div class="col-10">
            <div class="form-check form-check-inline">
              <%= form.collection_check_boxes :need_ids, Need.all, :id, :necessidade do |n| %>
              <div class="form-check-label">
                <%= n.check_box class: "form-check-input" %>
                <%= n.label %>
                &nbsp
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="actions card-footer">
    <%= form.submit "Salvar", class: "btn btn-primary"%>
    <%= link_to 'Voltar', root_path, class: "btn btn-primary float-right"%>
  </div>
<% end %>

app/views/institutions/_institution.html.erb
<div class='col-sm-6 col-lg-12'>
  <div class="card">
    <div class="card-header text-center">
      <h1><%= institution.name %></h1>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-sm-6 col-lg-12">
          <%= institution.description %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-6 col-lg-12">
          <strong>Necessidades: </strong><%= institution.needs.map(&:necessidade).join(", ") %>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-6">
          <div class="row">
            <div class="col-sm-6 col-lg-12">
              <strong>Endereço: </strong><%= institution.address %>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-6 col-lg-12">
              <div class="row"></div>
              <strong>Cidade: </strong><%= institution.city %>
              <strong>Estado: </strong><%= institution.state %>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="row">
            <strong>Phone:</strong> <%= institution.phone %>
          </div>
          <div class="row">
            <strong>E-mail:</strong> <%= institution.email %>
          </div>
        </div>
      </div>

    </div>
  </div>
  <br>
</div>

app/views/institutions/edit.html.erb
<h1>Editing Institution</h1>

<%= render 'form', institution: @institution %>

<%= link_to 'Destroy', @institution, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/institutions/index.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <div class="card-header">
    <h1>Instituições</h1>
  </div>
  <div class="card-body">
    <table class="table table-striped">
      <thead class="text-center">
        <tr>
          <th scope="col">Nome</th>
          <th scope="col">Cidade</th>
          <th scope="col">Estado</th>
          <th scope="col">Necessidades</th>
          <th scope="col">Descrição</th>
          <th scope="col" colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @institutions.each do |institution| %>
          <tr>
            <td><%= institution.name %></td>
            <td><%= institution.city %></td>
            <td><%= institution.state %></td>
            <td><%= institution.needs.map(&:necessidade).join(", ") %></td>
            <td><%= institution.description %></td>
            <td><%= link_to 'Ver mais', institution %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/institutions/new.html.erb
<div class="card">
  <div class="card-header">
    <h1>Nova Instituição</h1>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-md-12">
        <%= render 'form', institution: @institution %>       
      </div>
    </div>
  </div>
</div>

app/views/institutions/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
  <div class='col-sm-6 col-lg-12'>
    <div class="card">
      <div class="card-header text-center">
        <h1><%= @institution.name %></h1>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-sm-6 col-lg-12">
            <%= @institution.description %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6 col-lg-12">
            <strong>Necessidades: </strong><%= @institution.needs.map(&:necessidade).join(", ") %>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-6">
            <div class="row">
              <div class="col-sm-6 col-lg-12">
                <strong>Endereço: </strong><%= @institution.address %>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-6 col-lg-12">
                <div class="row"></div>
                <strong>Cidade: </strong><%= @institution.city %>
                <strong>Estado: </strong><%= @institution.state %>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="row">
              <strong>Phone:</strong> <%= @institution.phone %>
            </div>
            <div class="row">
              <strong>E-mail:</strong> <%= @institution.email %>
            </div>
          </div>
        </div>
  
      </div>
      <div class="card-footer">
        <%= link_to 'Voltar', institutions_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= image_tag("logo-menu.png", :alt => "Smiley face", class: "logo-menu", height: "45", width: "auto") %>
    <%= link_to 'ONDE DOAR', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
        
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Cadastre sua instituição', new_institution_path, class: "nav-link" %>
        </li>

        <li class="nav-item active">
          <%= link_to 'Instituições beneficiadas', institutions_path, class: "nav-link" %>
        </li>
        
        <li class="nav-item active">
          <%= link_to 'Quem somos', criadores_path, class: "nav-link" %>
        </li>

        <li class="nav-item active">
          <%= link_to 'Contato', contato_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OndeDoar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="principal">
    <%= render 'layouts/navbar' %>
        
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/needs/_form.html.erb
<%= form_with(model: need, local: true) do |form| %>
  <% if need.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(need.errors.count, "error") %> prohibited this need from being saved:</h2>

      <ul>
      <% need.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :necessidade %>
    <%= form.text_field :necessidade %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/needs/edit.html.erb
<h1>Editing Need</h1>

<%= render 'form', need: @need %>

<%= link_to 'Show', @need %> |
<%= link_to 'Back', needs_path %>

app/views/needs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Needs</h1>

<table>
  <thead>
    <tr>
      <th>Necessidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @needs.each do |need| %>
      <tr>
        <td><%= need.necessidade %></td>
        <td><%= link_to 'Show', need %></td>
        <td><%= link_to 'Edit', edit_need_path(need) %></td>
        <td><%= link_to 'Destroy', need, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Need', new_need_path %>

app/views/needs/new.html.erb
<h1>New Need</h1>

<%= render 'form', need: @need %>

<%= link_to 'Back', needs_path %>

app/views/needs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Necessidade:</strong>
  <%= @need.necessidade %>
</p>

<%= link_to 'Edit', edit_need_path(@need) %> |
<%= link_to 'Back', needs_path %>

app/views/pages/contato.html.erb
<div class="card">
  <div class="card-header">
    <h1>Fale conosco</h1>
  </div>
  <div class="card-body">
    <form>
      <div class="form-group">
        <label for="formGroupExampleInput">Nome</label>
        <input type="text" class="form-control" id="formGroupExampleInput" placeholder="nome completo">
      </div>
      <div class="form-group">
        <label for="exampleFormControlInput1">Email</label>
        <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="nome@exemplo.com">
      </div>
      <div class="form-group">
        <label for="exampleFormControlTextarea1">Deixe sua mensagem</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" placeholder="mensagem" rows="3"></textarea>
      </div>
      </form>
  </div>
  <div class="card-footer">
    <button type="button" class="btn btn-primary">Enviar</button>
  </div>
</div>

app/views/pages/criadores.html.erb
<div class="row">
  <div class="col-md-6" id ="titulo">
    Quem <br>somos
  </div>
  <div class="col-md-6">
    <div class="card-criadores">
      <div class="card-criadores-img">
        <%= image_tag("elsa.JPG", :alt => "...", class: "card-criadores-imagem") %>
      </div>
      <div class="card-criadores-txt">
        <h1 class="titulo-card">
          Marina
        </h1>
        <p class="p-txt">
          Estudante de ciência da computação da USP-SC, entrou em 2018, curte trabalho voluntário
          e ver vídeos aleatório do youtube, e no futuro pensa trabalhar com computação voltada
          à ações sociais.  
        </p>
      </div>
    </div>
    <div class="card-criadores">
      <div class="card-criadores-img">
        <%= image_tag("elsa.JPG", :alt => "...", class: "card-criadores-imagem") %>
      </div>
      <div class="card-criadores-txt">
        <h1 class="titulo-card">
          Luíza
        </h1>
        <p class="p-txt">
          Estudante de Ciências de Computação na Universidade de São Paulo, entusiasta da área
          de segurança da informação e eterna aprendiz de Programação Orientada a Objetos. O 
          coração dizia Java, mas a vida disse Ruby.
        </p>
      </div>
    </div>
    <div class="card-criadores">
      <div class="card-criadores-img">
        <%= image_tag("elsa.JPG", :alt => "...", class: "card-criadores-imagem") %>
      </div>
      <div class="card-criadores-txt">
        <h1 class="titulo-card">
          Moana
        </h1>
        <p class="p-txt">
          dfoihds fhusdhfushdufhwueihfuiweh ufihweiufhewuifhuiwehuweuifeuwh ui fhew
        </p>
      </div>
    </div>
    <div class="card-criadores">
      <div class="card-criadores-img">
        <%= image_tag("elsa.JPG", :alt => "...", class: "card-criadores-imagem") %>
      </div>
      <div class="card-criadores-txt">
        <h1 class="titulo-card">
          Tiana
        </h1>
        <p class="p-txt">
          dsfh jsdjfhsdjkfhjsdhf jskdhf jksdh ksdh fkjhsd kjfhskjhkjsfkh sk
        </p>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="text-center">
  <%= image_tag("logo.png", :alt => "logo onde doar", class: "logo-imagem img-fluid") %>
</div>

<div class="row">
  <div class="col-md-4">

  </div>
  <div class="col-md-4">
    <%= form_tag({:action=>"search", :controller => "pages"}, method: "get") do %>
      <div class="row form-group">
        <div class="col-md-12">
          <%= select_tag :state, options_for_select(State.all.map(&:name)), :class => 'form-control', :prompt => "Escolha um estado" %>
        </div>
      </div>
      <div class="row form-group">
        <div class="col-md-12">
          <%= grouped_collection_select :city, :city_id, @states, :cities, :name, :name, :name, {include_blank: true}, class: "form-control" %>
        </div>
      </div>
      <div class="row form-group">
        <div class="col-md-12">
          <%= select_tag :need, options_for_select(Need.all.map(&:necessidade)), :class => 'form-control', :prompt => "Escolha uma necessidade" %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 text-center">
          <%= submit_tag "Buscar", :id => "find-on-map", :class => "btn btn-primary btn-lg", :style => "width: 300px;" %>
        </div>    
      </div> 
      
        
    <% end %>
  </div>
  <div class="col-md-4">
  
  </div>
</div>

app/views/pages/search.html.erb
<div class="row">
  <%= render @institutions %>
</div>